---
apiVersion: v1
kind: Namespace
metadata:
  name: bggns

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgg-cm
  namespace: bggns
data:
  BGG_DB_USER: root
  BGG_DB_HOST: bggdb-svc.bggns.svc.cluster.local
  BGG_DB_PORT: "36000"
  BGG_PORT: "5000"

---
apiVersion: v1
kind: Secret
metadata:
  name: bgg-secret
  namespace: bggns
type: Opaque
stringData:
  # rootroot
  #BGG_DB_PASSWORD: cm9vdHJvb3Q=
  BGG_DB_PASSWORD: kYnyNNZXnGxcDnCmWflDnNPyePIQwxGk
