---
apiVersion: v1
kind: Namespace
metadata:
  name: code-ns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: code-cm
  namespace: code-ns
data:
  TZ: Asia/Singapore
  DEFAULT_WORKSPACE: /config/workspace
  PROXY_DOMAIN: code-146.190.201.253.sslip.io
---
apiVersion: v1
kind: Secret
metadata:
  name: code-secret
  namespace: code-ns
type: Opaque
data:
  PASSWORD: cGFzc3dvcmQ=
  SUDO_PASSWORD: cGFzc3dvcmQ=
