---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-ns

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-cm
  namespace: minio-ns
data:
  MINIO_ROOT_USER: root

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio-ns
type: Opaque
data:
  # rootroot
  MINIO_ROOT_PASSWORD: cm9vdHJvb3Q=
